### ISSUE TITLE
Need some information

### ISSUE THREAD

**Issue by Human79** [mdraan1/HP-Probook-430-G3-macos#1]
Hi
Just wanted to ask what SSDT-FANQ, SSDT-WLAN,SSDT-CARD,SSDT-HP-THRC are for?
Also the does the macOS Powerchime (the sound when you plug in the charger) work for you?
What do they do?
Regards.

**Comment by mdraan1** [comment]
> Hi
> Just wanted to ask what SSDT-FANQ, SSDT-WLAN,SSDT-CARD,SSDT-HP-THRC are for?
> Also the does the macOS Powerchime (the sound when you plug in the charger) work for you?
> What do they do?
> Regards.

Hi
SSDT-FANQ for better battery and quiet fan noise
SSDT-WLAN,SSDT-CARD,SSDT-HP-THRC only for make up in IORegistryExplorer
Also the does the macOS Powerchime (the sound when you plug in the charger) work for you?
Yes, but only in High Sierra and Mojave. I don´t remember if Catalina or BigSur.

This is my EFI folder for daily use without problems.

**Comment by Human79** [comment]
I do not get Fan reading in iSTATMenus. Cpu temperatures are fine though.

**Comment by mdraan1** [comment]
> I do not get Fan reading in iSTATMenus. Cpu temperatures are fine though.

It depend of VirtualSMC/FakeSMC/Hardware/Bios.
Try using plugins from repo VirtualSMC.

Don´t use both of them at the same time. (FakeSMC/VirtualSMC)

FakeSMC has better compatibility with old hardware, try it.
