### ISSUE TITLE
Does the macOS Powerchime work for you? (Big Sur)

### ISSUE THREAD

**Issue by Human79** [mdraan1/HP-Probook-430-G3-macos#2]
Does the macOS Powerchime (the sound when you plug in the charger) work for you?

**Comment by mdraan1** [comment]
> Does the macOS Powerchime (the sound when you plug in the charger) work for you?

Yes, it does.

**Comment by Human79** [comment]
Mine can be heard only using headphones. Any fix?
Edit: Though you have closed this, please answer my query.
Regards.

**Comment by mdraan1** [comment]
> Mine can be heard only using headphones. Any fix?
> Edit: Though you have closed this, please answer my query.
> Regards.

Try to change AppleALC layout ID from 3 to 5 or 7.
3 is working for me without issues.
