### ISSUE TITLE
Cannot boot from efi

### ISSUE THREAD

**Issue by robi62** [mdraan1/HP-Probook-430-G3-macos#3]
Hi I have used you efi folder as I have same laptop but if I edit the config file on next boot cursor goes crazy I cannot choose which disk I can boot from

**Comment by mdraan1** [comment]
> Hi I have used you efi folder as I have same laptop but if I edit the config file on next boot cursor goes crazy I cannot choose which disk I can boot from

Hi... Check your UEFI Bios version.
What are you editing?

**Comment by mdraan1** [comment]
> Hi I have used you efi folder as I have same laptop but if I edit the config file on next boot cursor goes crazy I cannot choose which disk I can boot from

If you are trying to modify the themes, just remember that you must use the same version of OC.

**Comment by robi62** [comment]
No Not the themes the actual config file to install different kext and so on
I tried different efi but none of them give me ubs at all strange I have checked bios options and are fine

**Comment by mdraan1** [comment]
> No Not the themes the actual config file to install different kext and so on
> I tried different efi but none of them give me ubs at all strange I have checked bios options and are fine

So weird because i don't have any problems, i recomend you check your bios version.
All my usb ports working out the box, wifi with ITLWM and Heliport, ethernet, etc.

Card Reader not working (NO ketxts available for now)

Remember:
Don't use configurators apps, just use opencore plist edit (ProperTree). Read carefully about how to use it.

Regards.

**Comment by robi62** [comment]
Hi I know y OpenCore configurator is responsible I never used propertree Lets hope is not too difficult to use

**Comment by mdraan1** [comment]
> Hi I know y OpenCore configurator is responsible I never used propertree Lets hope is not too difficult to use

Not difficult at all, try it and let me know.

Start using my clean EFI folder from scratch.
