### ISSUE TITLE
stuck at running package scripts

### ISSUE THREAD

**Issue by SiamSami** [mdraan1/HP-Probook-430-G3-macos#4]
as the title suggests...
can you explain how exactly you installed it?

**Comment by mdraan1** [comment]
> ass the title suggests... can you explain how exactly you installed it?

Just create a USB installer, then put the EFI folder inside of EFI partition.
Set de BIOS: Boot UEFI only, disable CSM and secure boot
Update the UEFI Bios to the latest release
Try again.
