### ISSUE TITLE
HDMI  sound doesn't work

### ISSUE THREAD

**Issue by robi62** [mdraan1/HP-Probook-430-G3-macos#5]
Hi its me again I tried your efi again everything good but when I connect hdmi to laptop I don't get the option for sound from tv
only internals speakers

**Comment by robi62** [comment]
I managed to Fix it thanks to OSx latitude add this to device
framebuffer-con1-enable 1 NUMBER
framebuffer-con1-type 00080000 DATA

**Comment by mdraan1** [comment]
> I managed to Fix it thanks to OSx latitude add this to device framebuffer-con1-enable 1 NUMBER framebuffer-con1-type 00080000 DATA

Hi, sorry for delay...
Great.

**Comment by robi62** [comment]
Try this one is really good https://github.com/Baio1977/HP-Probook-430-G3-Skylake
